#!/usr/bin/env python3

import argparse
import json
import logging
import sys

# Setup basic logging
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Calculate the optimal ordering (TSP) from an OpenRouteService matrix JSON file."
    )
    parser.add_argument(
        "-i",
        "--input",
        required=True,
        help="Path to the input JSON matrix file (generated by the matrix script).",
    )
    parser.add_argument(
        "-o",
        "--output",
        required=True,
        help="Path to save the optimized ordering results (JSON).",
    )
    parser.add_argument(
        "-m",
        "--metric",
        choices=["duration", "distance"],
        default="duration",
        help="Metric to optimize for: 'duration' (seconds) or 'distance' (meters). Default: duration",
    )
    parser.add_argument(
        "--open",
        action="store_true",
        help="Optimize for a one-way linear path instead of a round-trip loop.",
    )
    return parser.parse_args()


def load_matrix_data(filepath, metric):
    """Loads names and the chosen cost matrix from the JSON input file."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            data = json.load(f)

        names = data["names"]
        matrix_key = "durations_s" if metric == "duration" else "distances_m"

        if matrix_key not in data:
            raise KeyError(
                f"Expected matrix key '{matrix_key}' not found in input JSON."
            )

        matrix = data[matrix_key]
        return names, matrix

    except FileNotFoundError:
        logging.error(f"Input matrix file not found: {filepath}")
        sys.exit(1)
    except Exception as e:
        logging.error(f"Error loading matrix file: {e}")
        sys.exit(1)


def compute_tour_cost(tour, matrix, closed=True):
    """Calculates the total cost of a given tour sequence."""
    cost = sum(matrix[tour[i]][tour[i + 1]] for i in range(len(tour) - 1))
    if closed:
        cost += matrix[tour[-1]][tour[0]]
    return cost


def solve_tsp_nearest_neighbor(matrix, closed=True):
    """
    Generates a high-quality initial tour using the Nearest Neighbor heuristic.
    Tries every node as a starting position and returns the best sequence found.
    """
    n = len(matrix)
    best_tour = []
    best_cost = float("inf")

    for start_node in range(n):
        unvisited = set(range(n))
        unvisited.remove(start_node)
        current_node = start_node
        tour = [start_node]

        while unvisited:
            # Find closest unvisited neighbor
            next_node = min(unvisited, key=lambda x: matrix[current_node][x])
            unvisited.remove(next_node)
            tour.append(next_node)
            current_node = next_node

        cost = compute_tour_cost(tour, matrix, closed=closed)
        if cost < best_cost:
            best_cost = cost
            best_tour = tour

    return best_tour


def optimize_tsp_2opt(tour, matrix, closed=True):
    """
    Refines the initial tour using the 2-opt algorithm.
    Iteratively reverses segments of the path to untangle crossovers and reduce cost.
    """
    n = len(tour)
    best_tour = list(tour)
    best_cost = compute_tour_cost(best_tour, matrix, closed=closed)
    improved = True

    while improved:
        improved = False
        for i in range(1, n - 1):
            for j in range(i + 1, n):
                if j - i == 1:
                    continue  # Changes nothing to reverse adjacent nodes

                # Create a proposal tour reversing segment between i and j
                new_tour = best_tour[:]
                new_tour[i:j] = best_tour[i:j][::-1]
                new_cost = compute_tour_cost(new_tour, matrix, closed=closed)

                if new_cost < best_cost:
                    best_tour = new_tour
                    best_cost = new_cost
                    improved = True

        if not improved:
            break

    return best_tour, best_cost


def main():
    args = parse_args()
    is_closed_loop = not args.open

    logging.info(f"Loading matrix data from {args.input}...")
    names, matrix = load_matrix_data(args.input, args.metric)

    num_locations = len(names)
    if num_locations < 2:
        logging.error(
            "At least 2 locations are required to compute an optimal ordering."
        )
        return

    logging.info(
        f"Optimizing order for {num_locations} locations based on {args.metric}..."
    )
    logging.info(
        f"Route Type: {'Round-trip Loop' if is_closed_loop else 'One-way Linear Path'}"
    )

    # Step 1: Get an excellent starting seed tour
    initial_tour = solve_tsp_nearest_neighbor(matrix, closed=is_closed_loop)

    # Step 2: Fine-tune the path edges using 2-opt local search optimization
    optimal_indices, final_cost = optimize_tsp_2opt(
        initial_tour, matrix, closed=is_closed_loop
    )

    # Map indices back to names
    optimal_names = [names[idx] for idx in optimal_indices]

    # Construct structured output metrics
    unit = "meters" if args.metric == "distance" else "seconds"
    logging.info(f"Optimization complete! Optimal cost: {final_cost:,.2f} {unit}")

    output_data = {
        "optimization_metric": args.metric,
        "route_type": "round-trip" if is_closed_loop else "one-way",
        "total_cost": final_cost,
        "cost_unit": unit,
        "optimal_order_indices": optimal_indices,
        "optimal_order_names": optimal_names,
    }

    try:
        with open(args.output, "w", encoding="utf-8") as f:
            json.dump(output_data, f, indent=2)
        logging.info(f"Optimal ordering saved to {args.output}")
    except Exception as e:
        logging.error(f"Failed to write output to {args.output}: {e}")


if __name__ == "__main__":
    main()
